import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactGA from "react-ga4";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const TRACKING_ID = "G-XNM4GVQY8N";
ReactGA.initialize(TRACKING_ID);
ReactGA.send({ hitType: "pageview", page: "/" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${TRACKING_ID}`}
        />
        <Script id="ga-config">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '${TRACKING_ID}');
          `}
        </Script>
        <meta name="google-site-verification" content="R-S6B6lhsaI2qjOq6TxTMt-EVOGXYaL_i8EZLE7W1gA" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
